spring.application.name=sistema-gestion-signos-vitales

# Conexión JDBC usando el Transaction Pooler (Soporta IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.nsibmpifphnjajvtwikp
spring.datasource.password=proyecto123

# Driver JDBC de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Creación/Actualización automática de tablas desde JPA
spring.jpa.hibernate.ddl-auto=update

# Logs de SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#cd sistema-gestion-signos-vitales
#.\mvnw.cmd spring-boot:run

# Para detener el servidor: Si necesitas hacer cambios de código 
#que requieran reiniciar, haz clic en la terminal de VS Code y presiona Ctrl + C