spring.application.name=sistema-gestion-signos-vitales

# Conexión a PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://db.nsibmpifphnjajvtwikp.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=AQUÍ_TU_CONTRASEÑA

# Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Creación/Actualización automática de tablas desde Java
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true