# application.properties actúa como el centro de control de configuración de tu aplicación Spring Boot.
# Su función exacta es definir las reglas, credenciales y comportamientos del sistema sin modificar el código fuente en Java.

spring.application.name=sistema-gestion-signos-vitales

# ~ Conexión JDBC usando el Transaction Pooler (Soporta IPv4) ~
#-Transacción pooler: En lugar de abrir y cerrar conexiones reales a PostgreSQL continuamente, las gestiona 
#en un grupo(pool), reutilizándolas y haciendo la aplicación más estable
#-spring.datasource.url le dice al spring boot la ubicación exacta en internet de tu base de datos y cómo debe conectarse a ella
#-spring.datasource.username junto con password, son la llave de acceso para poder entrar a la base de datos de Supabase que
#configuraste en el paso anterior, sin esto, el servidor rechazará la conexión de Spring Boot por razones de seguridad
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require  
spring.datasource.username=postgres.nsibmpifphnjajvtwikp
spring.datasource.password=proyecto123

# ~ Driver JDBC de PostgreSQL ~
# Le dice a Spring Boot qué traductor específico debe usar para comunicarse con la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver
|
# ~ Creación/Actualización automática de tablas desde JPA ~
# Sirve para decirle a Hibernate(framework ORM) las reglas gramaticales específicas del lenguaje PostgreSQL
# Cuando pones código en Java(usando repositorios o JPA), Hibernate debe convertir eso a consultas SQL reales(SELECT, INSERT, etc)
# uptdate compara entidades en Java con las tablas existentes en la base de datos. Si agregas unanueva entidad, crea las tablas automáticamente sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update

# ~ Logs de SQL en consola ~
# Imprime en consola de la terminal las sentencias SQL reales que Hibernate ejecuta en la base de datos cuando realizas operaciones (consultar, guardar, actualizar, etc.).
spring.jpa.show-sql=true
# Toma esa línea larga y fea generada por la propiedad anterior y la organiza con saltos de línea y sangrías(indentación)
spring.jpa.properties.hibernate.format_sql=true


#.\mvnw.cmd spring-boot:run 
=======

#cd sistema-gestion-signos-vitales
#.\mvnw.cmd spring-boot:run
>>>>>>> b45edd87e7ad741544fa38fc4a52bed00c4b9aad

# Para detener el servidor: Si necesitas hacer cambios de código 
#que requieran reiniciar, haz clic en la terminal de VS Code y presiona Ctrl + C